receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: localhost:9091  # Configure prometeus to scrape from this endpoint
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      exporters: [jaeger]
